name: Backend .NET CI

on:
  workflow_dispatch:
  push:
    branches: ["main", "develop", "feature/*"]
    paths:
      - "backend-dotnet/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "backend-dotnet/**"

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend-dotnet

    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "zulu"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          export PATH="$PATH:/home/runner/.dotnet/tools"

      - name: Run SonarCloud Scan
        run: |
          dotnet sonarscanner begin \
            /k:"gasbrieo_todolab_backend-dotnet" \
            /n:"todolab_backend-dotnet" \
            /o:"gasbrieo" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.token="${{ secrets.BACKEND_DOTNET_SONAR_TOKEN }}" \
            /d:sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
          dotnet build --configuration Release
          dotnet test --configuration Release --no-build --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          dotnet sonarscanner end /d:sonar.token="${{ secrets.BACKEND_DOTNET_SONAR_TOKEN }}"
